config/routes.rb
Twitter::Application.routes.draw do
  root :to => "tweets#index"
  devise_for :users

  resources :replies

  resources :follows

  resources :tweets do
    member do
      post 'retweet'
    end
  end

  resources :users do
    collection do
      get 'count' 
    end
    member do
      post 'follow'
    end
  end
end

app/models/follow.rb
class Follow < ActiveRecord::Base
  belongs_to :user
end

app/models/reply.rb
class Reply < ActiveRecord::Base
  belongs_to :tweet
end

app/models/tweet.rb
class Tweet < ActiveRecord::Base
  belongs_to :user
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  has_many :tweets
  has_many :follows

  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
 
  has_attached_file :avatar, styles: { medium: "300x300", thumb: "100x100" }
  validates_attachment_content_type :avatar, content_type: /\Aimage\/.*\Z/
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
 
  protect_from_forgery with: :exception
   
  before_action :configure_permitted_parameters, if: :devise_controller?
 
  protected
 
  def configure_permitted_parameters
    devise_parameter_sanitizer.for(:sign_up) { |u| u.permit(:username, :email, :password, :password_confirmation, :remember_me, :avatar, :avatar_cache, :bio) }
    devise_parameter_sanitizer.for(:account_update) { |u| u.permit(:username, :password, :password_confirmation, :current_password, :avatar, :bio) }
  end
end

app/controllers/follows_controller.rb
class FollowsController < ApplicationController
  before_action :set_follow, only: [:show, :edit, :update, :destroy]

  respond_to :html

  def index
    @follows = Follow.all
    respond_with(@follows)
  end

  def show
    respond_with(@follow)
  end

  def new
    @follow = Follow.new
    respond_with(@follow)
  end

  def edit
  end

  def create
    @follow = Follow.new(follow_params)
    @follow.save
    respond_with(@follow)
  end

  def update
    @follow.update(follow_params)
    respond_with(@follow)
  end

  def destroy
    @follow.destroy
    respond_with(@follow)
  end

  private
    def set_follow
      @follow = Follow.find(params[:id])
    end

    def follow_params
      params.require(:follow).permit(:following, :user_id)
    end
end

app/controllers/replies_controller.rb
class RepliesController < ApplicationController
  before_action :set_reply, only: [:show, :edit, :update, :destroy]

  respond_to :html

  def index
    @replies = Reply.all
    respond_with(@replies)
  end

  def show
    respond_with(@reply)
  end

  def new
    @reply = Reply.new
    respond_with(@reply)
  end

  def edit
  end

  def create
    @reply = Reply.new(reply_params)
    @reply.save
    respond_with(@reply)
  end

  def update
    @reply.update(reply_params)
    respond_with(@reply)
  end

  def destroy
    @reply.destroy
    respond_with(@reply)
  end

  private
    def set_reply
      @reply = Reply.find(params[:id])
    end

    def reply_params
      params.require(:reply).permit(:comment, :tweet_id)
    end
end

app/controllers/tweets_controller.rb
class TweetsController < ApplicationController
  before_action :set_tweet, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!, only: [:new, :create, :update, :edit]

  respond_to :html

  def index
    @users = Follow.where(user_id: current_user.id).collect { |k| k.following }
    @tweets = Tweet.where(user_id: @users)
    respond_with(@tweets)
  end

  def show
    respond_with(@tweet)
  end

  def new
    @tweet = Tweet.new
    @tweet.user_id = current_user.id
    respond_with(@tweet)
  end

  def edit
  end

  def retweet
    @retweet = Tweet.create(message: set_tweet.message, user_id: set_tweet.user_id)
  end

  def create
    @tweet = Tweet.new(tweet_params)
    tweet_params.merge(user_id: current_user.id)
    @tweet.save
    respond_with(@tweet)
  end

  def update
    @tweet.update(tweet_params)
    respond_with(@tweet)
  end

  def destroy
    @tweet.destroy
    respond_with(@tweet)
  end

  private
    def set_tweet
      @tweet = Tweet.find(params[:id])
    end

    def tweet_params
      params.require(:tweet).permit(:message, :user_id)
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!

  def count
    @tweets_count = current_user.tweets.count
  end

  def index
    @users = User.all
  end

  def follow
    @check = Follow.where(user_id: current_user.id, following: params[:id]).first

    if @check.nil?
      @following = Follow.create(following: params[:id], user_id: current_user.id)
    else
      render json: { message: 'Already following' }, status: 400
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/follows_helper.rb
module FollowsHelper
end

app/helpers/replies_helper.rb
module RepliesHelper
end

app/helpers/tweets_helper.rb
module TweetsHelper
end

app/helpers/user_helper.rb
module UserHelper
end

app/views/follows/_form.html.erb
<%= form_for(@follow) do |f| %>
  <% if @follow.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@follow.errors.count, "error") %> prohibited this follow from being saved:</h2>

      <ul>
      <% @follow.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :following %><br>
    <%= f.number_field :following %>
  </div>
  <div class="field">
    <%= f.label :user_id %><br>
    <%= f.text_field :user_id %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/follows/edit.html.erb
<h1>Editing follow</h1>

<%= render 'form' %>

<%= link_to 'Show', @follow %> |
<%= link_to 'Back', follows_path %>

app/views/follows/index.html.erb
<h1>Listing follows</h1>

<table>
  <thead>
    <tr>
      <th>Following</th>
      <th>User</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @follows.each do |follow| %>
      <tr>
        <td><%= follow.following %></td>
        <td><%= follow.user %></td>
        <td><%= link_to 'Show', follow %></td>
        <td><%= link_to 'Edit', edit_follow_path(follow) %></td>
        <td><%= link_to 'Destroy', follow, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Follow', new_follow_path %>

app/views/follows/new.html.erb
<h1>New follow</h1>

<%= render 'form' %>

<%= link_to 'Back', follows_path %>

app/views/follows/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Following:</strong>
  <%= @follow.following %>
</p>

<p>
  <strong>User:</strong>
  <%= @follow.user %>
</p>

<%= link_to 'Edit', edit_follow_path(@follow) %> |
<%= link_to 'Back', follows_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Twitter</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<p class="notice"><%= notice %></p>
<p class="alert"><%= alert %></p>

<% if user_signed_in? %>
  <li>
    <%= link_to('Logout', destroy_user_session_path, method: :delete) %>        
  </li>
  <li>
  <%= link_to('Edit registration', edit_user_registration_path) %>
  </li>
<% else %>
  <li>
  <%= link_to('Register', new_user_registration_path)  %>
  </li>
  <li>
    <%= link_to('Login', new_user_session_path)  %>  
  </li>
<% end %>

<%= yield %>

</body>
</html>

app/views/replies/_form.html.erb
<%= form_for(@reply) do |f| %>
  <% if @reply.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@reply.errors.count, "error") %> prohibited this reply from being saved:</h2>

      <ul>
      <% @reply.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :comment %><br>
    <%= f.text_field :comment %>
  </div>
  <div class="field">
    <%= f.label :tweet_id %><br>
    <%= f.text_field :tweet_id %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/replies/edit.html.erb
<h1>Editing reply</h1>

<%= render 'form' %>

<%= link_to 'Show', @reply %> |
<%= link_to 'Back', replies_path %>

app/views/replies/index.html.erb
<h1>Listing replies</h1>

<table>
  <thead>
    <tr>
      <th>Comment</th>
      <th>Tweet</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @replies.each do |reply| %>
      <tr>
        <td><%= reply.comment %></td>
        <td><%= reply.tweet %></td>
        <td><%= link_to 'Show', reply %></td>
        <td><%= link_to 'Edit', edit_reply_path(reply) %></td>
        <td><%= link_to 'Destroy', reply, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Reply', new_reply_path %>

app/views/replies/new.html.erb
<h1>New reply</h1>

<%= render 'form' %>

<%= link_to 'Back', replies_path %>

app/views/replies/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Comment:</strong>
  <%= @reply.comment %>
</p>

<p>
  <strong>Tweet:</strong>
  <%= @reply.tweet %>
</p>

<%= link_to 'Edit', edit_reply_path(@reply) %> |
<%= link_to 'Back', replies_path %>

app/views/tweets/_form.html.erb
<%= form_for(@tweet) do |f| %>
  <% if @tweet.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@tweet.errors.count, "error") %> prohibited this tweet from being saved:</h2>

      <ul>
      <% @tweet.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :message %><br>
    <%= f.text_area :message %>
  </div>
  <div class="field">
    <%= f.label :user_id %><br>
    <%= f.text_field :user_id %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/tweets/edit.html.erb
<h1>Editing tweet</h1>

<%= render 'form' %>

<%= link_to 'Show', @tweet %> |
<%= link_to 'Back', tweets_path %>

app/views/tweets/index.html.erb
<h1>Listing tweets</h1>

<table>
  <thead>
    <tr>
      <th>Message</th>
      <th>User</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @tweets.each do |tweet| %>
      <tr>
        <td><%= tweet.message %></td>
        <td><%= tweet.user_id %></td>
        <td><%= link_to 'Show', tweet %></td>
        <td><%= link_to 'Edit', edit_tweet_path(tweet) %></td>
        <td><%= link_to 'Retweet', retweet_tweet_path(tweet.id), method: :post %></td>
        <td><%= link_to 'Destroy', tweet, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Tweet', new_tweet_path %>

app/views/tweets/new.html.erb
<h1>New tweet</h1>

<%= render 'form' %>

<%= link_to 'Back', tweets_path %>

app/views/tweets/retweet.html.erb
<h1> Retweeted </h1>

app/views/tweets/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Message:</strong>
  <%= @tweet.message %>
</p>

<p>
  <strong>User:</strong>
  <%= @tweet.user.id %>
</p>

<%= link_to 'Edit', edit_tweet_path(@tweet) %> |
<%= link_to 'Back', tweets_path %>

app/views/users/count.html.erb
<h1>Total tweets</h1>

<%= @tweets_count %>

<%= link_to 'New Tweet', new_tweet_path %>

app/views/users/edit.html.erb
<h1>User#edit</h1>
<p>Find me in app/views/user/edit.html.erb</p>

app/views/users/follow.html.erb
<h1>Followed</h1>

<%= link_to 'List of users', users_path %>

app/views/users/index.html.erb
<h1>Listing users</h1>

<table>
  <thead>
    <tr>
      <th>ID</th>
      <th>Email</th>
      <th>Bio</th>
      <th></th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= user.id %></td>
        <td><%= user.email %></td>
        <td><%= user.bio %></td>
        <% if !@check.present? %>
          <td><%= link_to 'Follow', follow_user_path(user.id), method: :post %></td>
        <% else %>
          <td> Following </td>  
        <% end %>
        <td><%= link_to 'Show', user %></td>
        <td><%= link_to 'Edit', edit_user_path(user) %></td>
        <td><%= link_to 'Destroy', user, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New User', new_user_path %>

app/views/users/show.html.erb
<h1>User#show</h1>
<p>Find me in app/views/user/show.html.erb</p>

app/views/users/update.html.erb
<h1>User#update</h1>
<p>Find me in app/views/user/update.html.erb</p>